# -*- coding: utf-8 -*-
"""ceyloncash-payments-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K8FNRrDyAhEblxi7ptK5HoVRiK2Fj6YJ
"""

#  Install & Import

!pip install plotly>=6.1.1 --quiet
!pip install kaleido --quiet

import importlib
import plotly.io as pio
importlib.reload(pio)

import os, sqlite3, zipfile, json
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
from plotly.io import to_html
from google.colab import files

# CELL 2 — Upload & Load Data

uploaded = files.upload()   # upload ceypay_analyst_task.db
conn = sqlite3.connect("ceypay_analyst_task.db")

transactions = pd.read_sql("SELECT * FROM transactions", conn)
merchants    = pd.read_sql("SELECT * FROM merchants",    conn)
chargebacks  = pd.read_sql("SELECT * FROM chargebacks",  conn)
settlements  = pd.read_sql("SELECT * FROM settlements",  conn)
conn.close()

# Parse dates
transactions["created_at"] = pd.to_datetime(transactions["created_at"])
chargebacks["created_at"]  = pd.to_datetime(chargebacks["created_at"])
settlements["settlement_date"] = pd.to_datetime(settlements["settlement_date"])

print("✅ Data loaded")
print(f"   transactions : {len(transactions):,} rows")
print(f"   merchants    : {len(merchants)} rows")
print(f"   chargebacks  : {len(chargebacks)} rows")
print(f"   settlements  : {len(settlements)} rows")

# CELL 3 — Shared Aggregations

MONTH_ORDER = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug"]

# ── Month fields ──────────────────────────────────────────────────
transactions["month_num"] = transactions["created_at"].dt.month
transactions["month_str"] = transactions["created_at"].dt.strftime("%b")
transactions["hour"]      = transactions["created_at"].dt.hour
chargebacks["month_num"]  = chargebacks["created_at"].dt.month
chargebacks["month_str"]  = chargebacks["created_at"].dt.strftime("%b")
settlements["month_num"]  = settlements["settlement_date"].dt.month
settlements["month_str"]  = settlements["settlement_date"].dt.strftime("%b")

# ── Monthly transaction summary ───────────────────────────────────
monthly = (
    transactions.groupby(["month_num","month_str"])
    .agg(
        total_txns   = ("transaction_id","count"),
        success_txns = ("status", lambda x: (x=="success").sum()),
        failed_txns  = ("status", lambda x: (x=="failed").sum()),
        revenue      = ("amount", lambda x: x[transactions.loc[x.index,"status"]=="success"].sum()),
    )
    .reset_index().sort_values("month_num")
)
monthly["success_rate"] = (monthly["success_txns"] / monthly["total_txns"] * 100).round(2)
monthly["revenue_mom"]  = monthly["revenue"].pct_change().mul(100).fillna(0).round(1)

# ── Monthly chargebacks ───────────────────────────────────────────
monthly_cb = (
    chargebacks.groupby(["month_num","month_str"])
    .agg(chargebacks_count=("chargeback_id","count"), cb_amount=("amount","sum"))
    .reset_index().sort_values("month_num")
)
# chargeback rate = cb / total_txns
monthly_cb = monthly_cb.merge(
    monthly[["month_num","total_txns"]], on="month_num", how="left"
)
monthly_cb["cb_rate"] = (monthly_cb["chargebacks_count"] / monthly_cb["total_txns"] * 100).round(3)

# ── Failure reason breakdown ──────────────────────────────────────
failure_counts = (
    transactions[transactions["status"]=="failed"]["failure_reason"]
    .value_counts().reset_index()
)
failure_counts.columns = ["reason","count"]
failure_counts["pct"] = (failure_counts["count"] / failure_counts["count"].sum() * 100).round(1)

# ── Failure reasons by month ──────────────────────────────────────
failure_by_month = (
    transactions[transactions["status"]=="failed"]
    .groupby(["month_str","failure_reason"])
    .size().reset_index(name="count")
)

# ── Hourly failure rate ───────────────────────────────────────────
hourly = (
    transactions.groupby("hour")
    .agg(total=("transaction_id","count"),
         failed=("status", lambda x: (x=="failed").sum()))
    .reset_index()
)
hourly["fr"] = (hourly["failed"] / hourly["total"] * 100).round(2)

# ── Merchant performance ──────────────────────────────────────────
tx_m = transactions.merge(merchants[["merchant_id","merchant_name","category","country"]], on="merchant_id")
merchant_perf = (
    tx_m.groupby(["merchant_id","merchant_name","category","country"])
    .agg(
        total   = ("transaction_id","count"),
        success = ("status", lambda x: (x=="success").sum()),
        revenue = ("amount", lambda x: x[tx_m.loc[x.index,"status"]=="success"].sum()),
    )
    .reset_index()
)
merchant_perf["sr"] = (merchant_perf["success"] / merchant_perf["total"] * 100).round(2)
merchant_perf = merchant_perf.sort_values("revenue", ascending=False)

# ── Category performance ──────────────────────────────────────────
cat_perf = (
    tx_m.groupby("category")
    .agg(
        total   = ("transaction_id","count"),
        success = ("status", lambda x: (x=="success").sum()),
        revenue = ("amount", lambda x: x[tx_m.loc[x.index,"status"]=="success"].sum()),
    )
    .reset_index()
)
cat_perf["sr"] = (cat_perf["success"] / cat_perf["total"] * 100).round(2)
cat_perf = cat_perf.sort_values("revenue", ascending=False)

# ── Settlement data ───────────────────────────────────────────────
set_m = settlements.merge(merchants[["merchant_id","merchant_name","category"]], on="merchant_id")
monthly_settlement = (
    settlements.groupby(["month_num","month_str"])
    .agg(settled_amount=("settled_amount","sum"))
    .reset_index().sort_values("month_num")
)
monthly_settlement = monthly_settlement.merge(monthly[["month_num","revenue"]], on="month_num", how="left")
monthly_settlement["fee"] = monthly_settlement["revenue"] - monthly_settlement["settled_amount"]
monthly_settlement["fee_rate"] = (monthly_settlement["fee"] / monthly_settlement["revenue"] * 100).round(2)

merchant_settlement = (
    set_m.groupby(["merchant_id","merchant_name"])
    .agg(settled=("settled_amount","sum"))
    .reset_index()
).merge(merchant_perf[["merchant_id","revenue","sr"]], on="merchant_id")
merchant_settlement["fee"] = merchant_settlement["revenue"] - merchant_settlement["settled"]
merchant_settlement["fee_rate"] = (merchant_settlement["fee"] / merchant_settlement["revenue"] * 100).round(2)
merchant_settlement = merchant_settlement.sort_values("settled", ascending=False)

# ── Currency / Geo ────────────────────────────────────────────────
geo_tx = tx_m.copy()
by_country = (
    geo_tx.groupby("country")
    .agg(
        total   = ("transaction_id","count"),
        success = ("status", lambda x: (x=="success").sum()),
        revenue = ("amount", lambda x: x[geo_tx.loc[x.index,"status"]=="success"].sum()),
    )
    .reset_index()
)
by_country["sr"] = (by_country["success"] / by_country["total"] * 100).round(2)
by_country["avg_txn"] = (by_country["revenue"] / by_country["success"]).round(2)
by_country = by_country.sort_values("revenue", ascending=False)

by_currency = (
    transactions.groupby("currency")
    .agg(
        total   = ("transaction_id","count"),
        success = ("status", lambda x: (x=="success").sum()),
        revenue = ("amount", lambda x: x[transactions.loc[x.index,"status"]=="success"].sum()),
    )
    .reset_index()
)
by_currency["sr"] = (by_currency["success"] / by_currency["total"] * 100).round(2)
by_currency = by_currency.sort_values("revenue", ascending=False)

# ── Chargeback by merchant ────────────────────────────────────────
cb_by_merchant = (
    chargebacks.merge(merchants[["merchant_id","merchant_name","category"]], on="merchant_id")
    .groupby(["merchant_id","merchant_name","category"])
    .agg(cb_count=("chargeback_id","count"), cb_amount=("amount","sum"))
    .reset_index()
).merge(merchant_perf[["merchant_id","total","revenue"]], on="merchant_id")
cb_by_merchant["cb_rate"] = (cb_by_merchant["cb_count"] / cb_by_merchant["total"] * 100).round(3)
cb_by_merchant = cb_by_merchant.sort_values("cb_count", ascending=False)

# ── Chargeback reasons ────────────────────────────────────────────
cb_reasons = (
    chargebacks.groupby("reason")
    .agg(count=("chargeback_id","count"), amount=("amount","sum"))
    .reset_index().sort_values("count", ascending=False)
)
cb_reasons["pct"] = (cb_reasons["count"] / cb_reasons["count"].sum() * 100).round(1)

# ── Global KPIs dict (shared across all dashboards) ───────────────
total_rev       = transactions[transactions["status"]=="success"]["amount"].sum()
total_settled   = settlements["settled_amount"].sum()
kpi_global = {
    "txns":      len(transactions),
    "rev":       round(total_rev, 2),
    "sr":        round((transactions["status"]=="success").mean()*100, 2),
    "cbs":       len(chargebacks),
    "merchants": merchants["merchant_id"].nunique(),
    "settled":   round(total_settled, 2),
}

print("✅ Aggregations ready")
print(f"   Total txns      : {kpi_global['txns']:,}")
print(f"   Total revenue   : ${kpi_global['rev']:,.2f}")
print(f"   Success rate    : {kpi_global['sr']}%")
print(f"   Total CBs       : {kpi_global['cbs']}")

# CELL 4 — KPI Console Summary

print("\n" + "="*55)
print("  CEYLONCASH KPIs  —  Jan–Aug 2024")
print("="*55)
print(f"  Total transactions  : {kpi_global['txns']:>10,}")
print(f"  Total revenue       : ${kpi_global['rev']:>12,.2f}")
print(f"  Overall success rate: {kpi_global['sr']:>9.2f}%")
print(f"  Total chargebacks   : {kpi_global['cbs']:>10,}")
print(f"  Total settled       : ${kpi_global['settled']:>12,.2f}")
print(f"  Platform fee rate   : {((kpi_global['rev']-kpi_global['settled'])/kpi_global['rev']*100):.2f}%")
print("="*55)

# CELL 5 — Shared HTML Helpers
# ══════════════════════════════════════════════════════════════════
os.makedirs("charts", exist_ok=True)

# ── Color palette ─────────────────────────────────────────────────
TEAL      = "#1D9E75"
RED       = "#E24B4A"
PURPLE    = "#534AB7"
AMBER     = "#BA7517"
LIGHT_RED = "#F09595"
GRAY      = "#888780"
BLUE      = "#378ADD"
ORANGE    = "#D85A30"

# ── Nav links (same across all pages) ────────────────────────────
NAV_LINKS = [
    ("index.html",      "📋 Storyboard"),
    ("platform.html",   "🏠 Platform Health"),
    ("merchant.html",   "🏪 Merchants"),
    ("failure.html",    "⚠️  Failure & Risk"),
    ("chargeback.html", "🔄 Chargebacks"),
    ("settlement.html", "💰 Settlement"),
    ("geo.html",        "🌏 Geo & Currency"),
]

def nav_html(active_file, accent_color):
    links = ""
    for href, label in NAV_LINKS:
        cls = 'active' if href == active_file else ''
        links += f'<a href="{href}" class="{cls}">{label}</a>'
    return f"""
<nav>
  <a class="nav-brand" href="index.html">Ceylon<span>Cash</span></a>
  <div class="nav-links">{links}</div>
</nav>"""

# ── Shared CSS (DM Sans, clean card grid) ────────────────────────
def base_css(accent):
    return f"""
:root{{
  --bg:#f0f2f5; --surface:#ffffff; --surface2:#f8f9fb;
  --border:#e4e7ec; --text:#1a1d23; --muted:#6b7280;
  --accent:{accent}; --radius:12px;
  --font:'DM Sans',sans-serif; --mono:'DM Mono',monospace;
}}
*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:var(--font);background:var(--bg);color:var(--text);min-height:100vh}}
nav{{background:var(--surface);border-bottom:1px solid var(--border);
     padding:0 32px;display:flex;align-items:center;gap:0;height:52px;
     position:sticky;top:0;z-index:100}}
.nav-brand{{font-size:15px;font-weight:600;color:var(--text);margin-right:32px;
            white-space:nowrap;text-decoration:none}}
.nav-brand span{{color:var(--accent)}}
.nav-links{{display:flex;gap:2px;overflow-x:auto;scrollbar-width:none}}
.nav-links::-webkit-scrollbar{{display:none}}
.nav-links a{{font-size:12px;font-weight:500;color:var(--muted);
              text-decoration:none;padding:6px 12px;border-radius:8px;
              white-space:nowrap;transition:all .15s}}
.nav-links a:hover{{color:var(--text);background:var(--surface2)}}
.nav-links a.active{{color:var(--accent);background:var(--surface2);font-weight:600}}
.page{{max-width:1380px;margin:0 auto;padding:28px 32px 48px}}
.page-header{{margin-bottom:24px}}
.page-header h1{{font-size:22px;font-weight:600;display:flex;align-items:center;gap:10px}}
.page-header h1 .icon{{width:32px;height:32px;border-radius:8px;
                        background:var(--accent);display:flex;align-items:center;
                        justify-content:center;font-size:16px}}
.page-header p{{font-size:13px;color:var(--muted);margin-top:6px}}
.kpi-row{{display:grid;gap:12px;margin-bottom:20px}}
.kpi-row-4{{grid-template-columns:repeat(4,1fr)}}
.kpi-row-5{{grid-template-columns:repeat(5,1fr)}}
.kpi{{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);
      padding:16px 20px}}
.kpi-label{{font-size:11px;font-weight:500;color:var(--muted);
            text-transform:uppercase;letter-spacing:.06em;margin-bottom:8px}}
.kpi-value{{font-size:24px;font-weight:600;color:var(--accent)}}
.kpi-value.neutral{{color:var(--text)}}
.grid{{display:grid;gap:16px;margin-bottom:16px}}
.grid-1{{grid-template-columns:1fr}}
.grid-2{{grid-template-columns:1fr 1fr}}
.grid-3{{grid-template-columns:1fr 1fr 1fr}}
.grid-2-1{{grid-template-columns:2fr 1fr}}
.grid-1-2{{grid-template-columns:1fr 2fr}}
.card{{background:var(--surface);border:1px solid var(--border);
       border-radius:var(--radius);padding:4px;overflow:hidden}}
.insight{{background:var(--surface2);border:1px solid var(--border);
          border-radius:var(--radius);padding:18px 20px;font-size:13px;
          line-height:1.65;color:var(--muted)}}
.insight strong{{color:var(--text);font-weight:600}}
table{{width:100%;border-collapse:collapse;font-size:12.5px}}
th{{font-weight:600;color:var(--muted);text-transform:uppercase;font-size:11px;
    letter-spacing:.04em;padding:8px 12px;border-bottom:1px solid var(--border);
    text-align:left;background:var(--surface2)}}
td{{padding:8px 12px;border-bottom:1px solid var(--border);color:var(--text)}}
tr:last-child td{{border-bottom:none}}
tr:hover td{{background:var(--surface2)}}
.badge{{display:inline-block;padding:2px 8px;border-radius:20px;
        font-size:11px;font-weight:600}}
.badge-red{{background:#fef2f2;color:{RED}}}
.badge-green{{background:#f0fdf4;color:{TEAL}}}
.badge-blue{{background:#eff6ff;color:{BLUE}}}
.badge-amber{{background:#fffbeb;color:{AMBER}}}
"""

# ── Plotly default layout ─────────────────────────────────────────
def default_layout(title, height=360):
    return dict(
        title=dict(text=title, font=dict(size=14, family="DM Sans"), pad=dict(l=8)),
        height=height,
        plot_bgcolor="white", paper_bgcolor="white",
        margin=dict(t=52, b=48, l=62, r=48),
        font=dict(family="DM Sans", size=12),
    )

# ── Convert fig → inline HTML div ────────────────────────────────
def div(fig):
    return to_html(fig, full_html=False, include_plotlyjs=False)

# ── Full page wrapper ─────────────────────────────────────────────
def page_wrap(active_file, accent, icon_emoji, title, subtitle, body_html):
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>CeylonCash — {title}</title>
<script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600&family=DM+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>
{base_css(accent)}
</style>
</head>
<body>
{nav_html(active_file, accent)}
<div class="page">
  <div class="page-header">
    <h1><span class="icon">{icon_emoji}</span>{title}</h1>
    <p>{subtitle}</p>
  </div>
  {body_html}
</div>
</body>
</html>"""

# ── KPI card helper ───────────────────────────────────────────────
def kpi(label, value, color_class=""):
    return f"""<div class="kpi">
      <div class="kpi-label">{label}</div>
      <div class="kpi-value {color_class}">{value}</div>
    </div>"""

def save(filename, html):
    path = f"charts/{filename}"
    with open(path,"w",encoding="utf-8") as f:
        f.write(html)
    print(f"  ✅ Saved → {path}")

print("✅ Helpers defined")

# CELL 6 — platform.html  (Platform Health Overview)

avg_sr = monthly["success_rate"].mean()
mom    = monthly["revenue_mom"]

# Chart 1 — Volume + Revenue (stacked bar + line)
f1 = make_subplots(specs=[[{"secondary_y":True}]])
f1.add_trace(go.Bar(
    name="Successful", x=MONTH_ORDER, y=monthly["success_txns"],
    marker_color=TEAL, offsetgroup=0), secondary_y=False)
f1.add_trace(go.Bar(
    name="Failed", x=MONTH_ORDER, y=monthly["failed_txns"],
    marker_color=RED, offsetgroup=0, base=monthly["success_txns"]), secondary_y=False)
f1.add_trace(go.Scatter(
    name="Revenue ($)", x=MONTH_ORDER, y=monthly["revenue"],
    mode="lines+markers",
    line=dict(color=PURPLE,width=2.5),
    marker=dict(size=7,color=PURPLE)), secondary_y=True)
f1.update_layout(**default_layout("Monthly transaction volume & revenue", 380))
f1.update_layout(barmode="stack",
    legend=dict(orientation="h",y=1.13,x=0),
    xaxis=dict(showgrid=False,categoryorder="array",categoryarray=MONTH_ORDER))
f1.update_yaxes(title_text="Transaction count",secondary_y=False,showgrid=True,gridcolor="#ebebeb")
f1.update_yaxes(title_text="Revenue ($)",secondary_y=True,showgrid=False,
                range=[700000,1060000],tickformat=",.0f")

# Chart 2 — Success rate trend
pt_colors = [RED if r < 90 else TEAL for r in monthly["success_rate"]]
f2 = go.Figure()
f2.add_trace(go.Scatter(
    x=MONTH_ORDER, y=monthly["success_rate"],
    mode="lines+markers",
    line=dict(color=TEAL,width=2.5),
    marker=dict(size=9,color=pt_colors,line=dict(width=1.5,color="white")),
    fill="tozeroy", fillcolor="rgba(29,158,117,0.08)", showlegend=False))
f2.add_hline(y=avg_sr,line_dash="dot",line_color=GRAY,line_width=1.5,
             annotation_text=f"Avg {avg_sr:.1f}%",annotation_position="top right")
f2.update_layout(**default_layout("Monthly success rate — June dip highlighted"))
f2.update_layout(
    xaxis=dict(showgrid=False,categoryorder="array",categoryarray=MONTH_ORDER,range=[-0.5,7.5]),
    yaxis=dict(range=[88,94],ticksuffix="%",showgrid=True,gridcolor="#ebebeb"))

# Chart 3 — Failure reason donut
labels_pct = [f"{r}<br>{p}%" for r,p in zip(failure_counts["reason"],failure_counts["pct"])]
f3 = go.Figure(go.Pie(
    labels=labels_pct, values=failure_counts["count"],
    hole=0.60,
    marker=dict(colors=[RED,AMBER,BLUE,GRAY]),
    textinfo="label", textposition="outside", textfont=dict(size=11),
    showlegend=False))
f3.update_layout(**default_layout("Failure reason breakdown"))
f3.update_layout(margin=dict(t=52,b=20,l=80,r=80),
    annotations=[dict(text=f"<b>{failure_counts['count'].sum():,}</b><br>failed",
                      x=0.5,y=0.5,font_size=14,showarrow=False)])

# Chart 4 — Chargeback trend
cb_colors_m = [RED if v >= 50 else LIGHT_RED for v in monthly_cb["chargebacks_count"]]
f4 = go.Figure(go.Bar(
    x=monthly_cb["month_str"], y=monthly_cb["chargebacks_count"],
    marker_color=cb_colors_m, marker_line_width=0,
    text=monthly_cb["chargebacks_count"], textposition="outside", textfont=dict(size=12)))
f4.update_layout(**default_layout("Monthly chargebacks — bars ≥ 50 flagged red"))
f4.update_layout(showlegend=False,
    xaxis=dict(showgrid=False,categoryorder="array",categoryarray=monthly_cb["month_str"].tolist()),
    yaxis=dict(showgrid=True,gridcolor="#ebebeb",range=[0,72]))

# Chart 5 — MoM Revenue
bar_c5 = [TEAL if v >= 0 else RED for v in mom]
f5 = go.Figure(go.Bar(
    x=MONTH_ORDER, y=mom.round(1),
    marker_color=bar_c5, marker_line_width=0,
    text=[f"{v:+.1f}%" for v in mom.round(1)],
    textposition="outside", textfont=dict(size=12)))
f5.add_hline(y=0,line_color=GRAY,line_width=1)
f5.update_layout(**default_layout("Revenue month-on-month % change"))
f5.update_layout(showlegend=False,
    xaxis=dict(showgrid=False,categoryorder="array",categoryarray=MONTH_ORDER),
    yaxis=dict(ticksuffix="%",showgrid=True,gridcolor="#ebebeb",range=[-16,10]))

# KPI row
kpis_p = f"""<div class="kpi-row kpi-row-4">
  {kpi("Total transactions", f"{kpi_global['txns']:,}", "")}
  {kpi("Total revenue", f"${kpi_global['rev']:,.0f}", "")}
  {kpi("Overall success rate", f"{kpi_global['sr']:.2f}%", "")}
  {kpi("Total chargebacks", str(kpi_global['cbs']), "")}
</div>"""

body_p = f"""{kpis_p}
<div class="grid grid-1" style="margin-bottom:16px"><div class="card">{div(f1)}</div></div>
<div class="grid grid-2" style="margin-bottom:16px">
  <div class="card">{div(f2)}</div>
  <div class="card">{div(f3)}</div>
</div>
<div class="grid grid-1" style="margin-bottom:16px"><div class="card">{div(f4)}</div></div>
<div class="grid grid-1"><div class="card">{div(f5)}</div></div>"""

save("platform.html", page_wrap(
    "platform.html", TEAL, "🏠",
    "Platform Health Overview",
    "Jan – Aug 2024 · Platform-wide metrics across 10 merchants",
    body_p))

# CELL 7 — merchant.html  (Merchant Performance)

# Chart m1 — Revenue by merchant (horizontal bar)
m1 = go.Figure(go.Bar(
    x=merchant_perf["revenue"],
    y=merchant_perf["merchant_name"],
    orientation="h",
    marker_color=PURPLE,
    text=[f"${v:,.0f}" for v in merchant_perf["revenue"]],
    textposition="outside", textfont=dict(size=11),
))
m1.update_layout(**default_layout("Total revenue by merchant", 380))
m1.update_layout(
    yaxis=dict(autorange="reversed", showgrid=False),
    xaxis=dict(showgrid=True, gridcolor="#ebebeb", tickformat=",.0f"),
    margin=dict(t=52,b=48,l=130,r=90), showlegend=False)

# Chart m2 — Success rate by merchant (scatter with reference line)
avg_sr_all = merchant_perf["sr"].mean()
dot_colors = [RED if v < avg_sr_all else TEAL for v in merchant_perf["sr"]]
m2 = go.Figure(go.Bar(
    x=merchant_perf["merchant_name"],
    y=merchant_perf["sr"],
    marker_color=dot_colors,
    text=[f"{v:.1f}%" for v in merchant_perf["sr"]],
    textposition="outside", textfont=dict(size=11),
))
m2.add_hline(y=avg_sr_all, line_dash="dot", line_color=GRAY, line_width=1.5,
             annotation_text=f"Avg {avg_sr_all:.1f}%", annotation_position="top right")
m2.update_layout(**default_layout("Success rate by merchant"))
m2.update_layout(
    xaxis=dict(showgrid=False, tickangle=-20),
    yaxis=dict(range=[84, 94], ticksuffix="%", showgrid=True, gridcolor="#ebebeb"),
    showlegend=False)

# Chart m3 — Category breakdown (pie)
m3 = go.Figure(go.Pie(
    labels=cat_perf["category"], values=cat_perf["revenue"],
    hole=0.55,
    marker=dict(colors=[PURPLE, TEAL, BLUE, AMBER, RED, ORANGE]),
    textinfo="label+percent", textposition="outside", textfont=dict(size=11),
    showlegend=False,
))
m3.update_layout(**default_layout("Revenue share by category"))
m3.update_layout(margin=dict(t=52,b=20,l=60,r=60),
    annotations=[dict(text=f"<b>6</b><br>categories",x=0.5,y=0.5,font_size=13,showarrow=False)])

# Chart m4 — Transaction volume vs success rate bubble
m4 = go.Figure()
for _, row in merchant_perf.iterrows():
    m4.add_trace(go.Scatter(
        x=[row["total"]], y=[row["sr"]],
        mode="markers+text",
        marker=dict(size=row["revenue"]/50000, color=PURPLE, opacity=0.75,
                    line=dict(width=1.5, color="white")),
        text=[row["merchant_name"]], textposition="top center",
        textfont=dict(size=10), showlegend=False,
        hovertemplate=f"<b>{row['merchant_name']}</b><br>Txns: {row['total']:,}<br>SR: {row['sr']:.1f}%<br>Rev: ${row['revenue']:,.0f}<extra></extra>"
    ))
m4.add_hline(y=avg_sr_all, line_dash="dot", line_color=GRAY, line_width=1,
             annotation_text=f"Avg SR {avg_sr_all:.1f}%", annotation_position="top right")
m4.update_layout(**default_layout("Volume vs success rate (bubble = revenue)"))
m4.update_layout(
    xaxis=dict(title="Transaction volume", showgrid=True, gridcolor="#ebebeb"),
    yaxis=dict(title="Success rate (%)", range=[84,95], ticksuffix="%",
               showgrid=True, gridcolor="#ebebeb"),
    showlegend=False)

# Merchant table
tbl_rows = ""
for _, row in merchant_perf.iterrows():
    badge = f'<span class="badge badge-red">⚠ {row["sr"]:.1f}%</span>' if row["sr"] < avg_sr_all \
            else f'<span class="badge badge-green">{row["sr"]:.1f}%</span>'
    tbl_rows += f"""<tr>
      <td><strong>{row["merchant_name"]}</strong></td>
      <td>{row["category"]}</td>
      <td>{row["country"]}</td>
      <td style="text-align:right">{row["total"]:,}</td>
      <td style="text-align:right">${row["revenue"]:,.0f}</td>
      <td style="text-align:right">{badge}</td>
    </tr>"""

merchant_table = f"""<div class="card" style="padding:0;overflow:auto">
  <table>
    <thead><tr>
      <th>Merchant</th><th>Category</th><th>Country</th>
      <th style="text-align:right">Transactions</th>
      <th style="text-align:right">Revenue</th>
      <th style="text-align:right">Success rate</th>
    </tr></thead>
    <tbody>{tbl_rows}</tbody>
  </table>
</div>"""

top_merchant = merchant_perf.iloc[0]
low_sr_m     = merchant_perf.loc[merchant_perf["sr"].idxmin()]

kpis_m = f"""<div class="kpi-row kpi-row-5">
  {kpi("Active merchants",     str(kpi_global["merchants"]))}
  {kpi("Top merchant revenue", f"${top_merchant['revenue']:,.0f}")}
  {kpi("Lowest success rate",  f"{low_sr_m['sr']:.1f}% ({low_sr_m['merchant_name']})")}
  {kpi("Top category",         cat_perf.iloc[0]["category"])}
  {kpi("Avg success rate",     f"{avg_sr_all:.1f}%")}
</div>"""

body_m = f"""{kpis_m}
<div class="grid grid-1" style="margin-bottom:16px"><div class="card">{div(m1)}</div></div>
<div class="grid grid-2" style="margin-bottom:16px">
  <div class="card">{div(m2)}</div>
  <div class="card">{div(m3)}</div>
</div>
<div class="grid grid-1" style="margin-bottom:16px"><div class="card">{div(m4)}</div></div>
{merchant_table}"""

save("merchant.html", page_wrap(
    "merchant.html", PURPLE, "🏪",
    "Merchant Performance",
    "Revenue, transaction volume & success rate across all merchants",
    body_m))

# CELL 8 — failure.html  (Failure & Risk Analysis)

total_failed  = (transactions["status"]=="failed").sum()
failure_rate  = total_failed / len(transactions) * 100
worst_reason  = failure_counts.iloc[0]["reason"]
june_card_dec = failure_by_month[
    (failure_by_month["month_str"]=="Jun") &
    (failure_by_month["failure_reason"]=="card_declined")
]["count"].values[0]

# Chart f1 — Stacked area: failure reasons over time
reasons = failure_counts["reason"].tolist()
reason_colors = [RED, AMBER, BLUE, GRAY]
f_fig1 = go.Figure()
for i, reason in enumerate(reasons):
    sub = failure_by_month[failure_by_month["failure_reason"]==reason].copy()
    sub = sub.set_index("month_str").reindex(MONTH_ORDER).fillna(0).reset_index()
    f_fig1.add_trace(go.Bar(
        name=reason.replace("_"," ").title(),
        x=sub["month_str"], y=sub["count"],
        marker_color=reason_colors[i % len(reason_colors)],
    ))
f_fig1.update_layout(**default_layout("Failure reasons by month — card_declined spike in June", 380))
f_fig1.update_layout(
    barmode="stack",
    legend=dict(orientation="h", y=1.12, x=0),
    xaxis=dict(showgrid=False, categoryorder="array", categoryarray=MONTH_ORDER),
    yaxis=dict(showgrid=True, gridcolor="#ebebeb", title="Failed transactions"))

# Chart f2 — Failure rate by hour heatmap-style bar
hr_colors = [RED if v > hourly["fr"].quantile(0.75) else TEAL for v in hourly["fr"]]
f_fig2 = go.Figure(go.Bar(
    x=hourly["hour"], y=hourly["fr"],
    marker_color=hr_colors, marker_line_width=0,
    hovertemplate="Hour %{x}:00 — Failure rate: %{y:.2f}%<extra></extra>",
))
f_fig2.add_hline(y=hourly["fr"].mean(), line_dash="dot", line_color=GRAY, line_width=1.5,
                 annotation_text=f"Avg {hourly['fr'].mean():.2f}%",
                 annotation_position="top right")
f_fig2.update_layout(**default_layout("Failure rate by hour of day"))
f_fig2.update_layout(
    xaxis=dict(showgrid=False, title="Hour (UTC)", dtick=2),
    yaxis=dict(showgrid=True, gridcolor="#ebebeb", ticksuffix="%", title="Failure rate"),
    showlegend=False)

# Chart f3 — Failure reason donut (full detail)
f_fig3 = go.Figure(go.Pie(
    labels=[f"{r}<br>{p}%" for r,p in zip(failure_counts["reason"],failure_counts["pct"])],
    values=failure_counts["count"],
    hole=0.60,
    marker=dict(colors=[RED, AMBER, BLUE, GRAY]),
    textinfo="label", textposition="outside", textfont=dict(size=11),
    showlegend=False,
))
f_fig3.update_layout(**default_layout("Overall failure reason distribution"))
f_fig3.update_layout(margin=dict(t=52,b=20,l=80,r=80),
    annotations=[dict(text=f"<b>{total_failed:,}</b><br>failed",
                      x=0.5, y=0.5, font_size=14, showarrow=False)])

# Chart f4 — Failure rate by merchant
fail_by_merch = merchant_perf[["merchant_name","total","success","sr"]].copy()
fail_by_merch["failed"] = fail_by_merch["total"] - fail_by_merch["success"]
fail_by_merch["fr"]     = (100 - fail_by_merch["sr"]).round(2)
fail_by_merch = fail_by_merch.sort_values("fr", ascending=True)

fr_colors = [RED if v > (100-avg_sr_all) else TEAL for v in fail_by_merch["fr"]]
f_fig4 = go.Figure(go.Bar(
    x=fail_by_merch["fr"], y=fail_by_merch["merchant_name"],
    orientation="h",
    marker_color=fr_colors, marker_line_width=0,
    text=[f"{v:.1f}%" for v in fail_by_merch["fr"]],
    textposition="outside", textfont=dict(size=11),
))
f_fig4.add_vline(x=(100-avg_sr_all), line_dash="dot", line_color=GRAY, line_width=1.5,
                 annotation_text=f"Avg {100-avg_sr_all:.1f}%",
                 annotation_position="top right")
f_fig4.update_layout(**default_layout("Failure rate by merchant"))
f_fig4.update_layout(
    yaxis=dict(showgrid=False),
    xaxis=dict(showgrid=True, gridcolor="#ebebeb", ticksuffix="%"),
    margin=dict(t=52,b=48,l=130,r=80), showlegend=False)

kpis_f = f"""<div class="kpi-row kpi-row-4">
  {kpi("Total failed transactions", f"{total_failed:,}")}
  {kpi("Overall failure rate",      f"{failure_rate:.2f}%")}
  {kpi("Worst failure reason",      worst_reason.replace("_"," ").title())}
  {kpi("June card decline spike",   f"{june_card_dec} txns")}
</div>"""

insight_f = """<div class="insight">
  <strong>Key finding — June card_declined anomaly.</strong>
  In June 2024, <em>card_declined</em> failures spiked to <strong>566</strong> — more than
  double the monthly average of ~248. All other failure reasons remained flat,
  suggesting a targeted payment processor or card-scheme issue rather than a systemic
  platform problem. The anomaly resolved by July, pointing to a temporary outage or
  rule change at the issuing bank / payment gateway level.
</div>"""

body_f = f"""{kpis_f}
<div class="grid grid-1" style="margin-bottom:16px"><div class="card">{div(f_fig1)}</div></div>
<div class="grid grid-2" style="margin-bottom:16px">
  <div class="card">{div(f_fig3)}</div>
  <div class="card">{div(f_fig2)}</div>
</div>
<div class="grid grid-1" style="margin-bottom:16px"><div class="card">{div(f_fig4)}</div></div>
{insight_f}"""

save("failure.html", page_wrap(
    "failure.html", RED, "⚠️",
    "Failure & Risk Analysis",
    "Transaction failure patterns, reasons, and merchant-level risk",
    body_f))

# CELL 9 — chargeback.html  (Chargeback Monitoring)

total_cb_amt  = chargebacks["amount"].sum()
highest_cb_m  = cb_by_merchant.iloc[0]
peak_cb_month = monthly_cb.loc[monthly_cb["chargebacks_count"].idxmax(), "month_str"]

# Chart cb1 — Monthly CB count + rate dual axis
cb1 = make_subplots(specs=[[{"secondary_y":True}]])
cb_bar_colors = [RED if v >= 50 else LIGHT_RED for v in monthly_cb["chargebacks_count"]]
cb1.add_trace(go.Bar(
    name="Chargebacks", x=monthly_cb["month_str"], y=monthly_cb["chargebacks_count"],
    marker_color=cb_bar_colors, marker_line_width=0,
    text=monthly_cb["chargebacks_count"], textposition="outside", textfont=dict(size=11)),
    secondary_y=False)
cb1.add_trace(go.Scatter(
    name="CB rate (%)", x=monthly_cb["month_str"], y=monthly_cb["cb_rate"],
    mode="lines+markers",
    line=dict(color=AMBER, width=2.5), marker=dict(size=7, color=AMBER)),
    secondary_y=True)
cb1.update_layout(**default_layout("Monthly chargebacks & chargeback rate", 380))
cb1.update_layout(
    barmode="group",
    legend=dict(orientation="h", y=1.12, x=0),
    xaxis=dict(showgrid=False, categoryorder="array",
               categoryarray=monthly_cb["month_str"].tolist()))
cb1.update_yaxes(title_text="Chargeback count", secondary_y=False,
                 showgrid=True, gridcolor="#ebebeb", range=[0,72])
cb1.update_yaxes(title_text="CB rate (%)", secondary_y=True,
                 showgrid=False, ticksuffix="%")

# Chart cb2 — CB by merchant (horizontal bar)
cb2 = go.Figure(go.Bar(
    x=cb_by_merchant["cb_count"],
    y=cb_by_merchant["merchant_name"],
    orientation="h",
    marker_color=AMBER, marker_line_width=0,
    text=cb_by_merchant["cb_count"], textposition="outside", textfont=dict(size=11),
))
cb2.update_layout(**default_layout("Chargebacks by merchant"))
cb2.update_layout(
    yaxis=dict(autorange="reversed", showgrid=False),
    xaxis=dict(showgrid=True, gridcolor="#ebebeb"),
    margin=dict(t=52,b=48,l=130,r=60), showlegend=False)

# Chart cb3 — CB reason donut
cb3 = go.Figure(go.Pie(
    labels=[f"{r}<br>{p}%" for r,p in zip(cb_reasons["reason"],cb_reasons["pct"])],
    values=cb_reasons["count"],
    hole=0.58,
    marker=dict(colors=[AMBER, RED, BLUE, GRAY, ORANGE]),
    textinfo="label", textposition="outside", textfont=dict(size=11),
    showlegend=False,
))
cb3.update_layout(**default_layout("Chargeback reason breakdown"))
cb3.update_layout(margin=dict(t=52,b=20,l=80,r=80),
    annotations=[dict(text=f"<b>{cb_reasons['count'].sum():,}</b><br>total",
                      x=0.5, y=0.5, font_size=14, showarrow=False)])

# Chart cb4 — CB rate by merchant scatter
cb4_data = cb_by_merchant.sort_values("cb_rate", ascending=False)
cb4_colors = [RED if v > cb_by_merchant["cb_rate"].mean() else AMBER for v in cb4_data["cb_rate"]]
cb4 = go.Figure(go.Bar(
    x=cb4_data["merchant_name"], y=cb4_data["cb_rate"],
    marker_color=cb4_colors, marker_line_width=0,
    text=[f"{v:.2f}%" for v in cb4_data["cb_rate"]],
    textposition="outside", textfont=dict(size=11),
))
cb4.add_hline(y=cb_by_merchant["cb_rate"].mean(), line_dash="dot", line_color=GRAY,
              annotation_text=f"Avg {cb_by_merchant['cb_rate'].mean():.2f}%",
              annotation_position="top right")
cb4.update_layout(**default_layout("Chargeback rate by merchant (% of transactions)"))
cb4.update_layout(
    xaxis=dict(showgrid=False, tickangle=-20),
    yaxis=dict(showgrid=True, gridcolor="#ebebeb", ticksuffix="%"),
    showlegend=False)

kpis_cb = f"""<div class="kpi-row kpi-row-4">
  {kpi("Total chargebacks",   str(kpi_global["cbs"]))}
  {kpi("Total disputed amount", f"${total_cb_amt:,.0f}")}
  {kpi("Highest CB rate",     f"{highest_cb_m['merchant_name']} ({highest_cb_m['cb_rate']:.2f}%)")}
  {kpi("Peak month",          peak_cb_month)}
</div>"""

body_cb = f"""{kpis_cb}
<div class="grid grid-1" style="margin-bottom:16px"><div class="card">{div(cb1)}</div></div>
<div class="grid grid-2" style="margin-bottom:16px">
  <div class="card">{div(cb2)}</div>
  <div class="card">{div(cb3)}</div>
</div>
<div class="grid grid-1"><div class="card">{div(cb4)}</div></div>"""

save("chargeback.html", page_wrap(
    "chargeback.html", AMBER, "🔄",
    "Chargeback Monitoring",
    "Dispute trends, reason codes, and merchant-level chargeback rates",
    body_cb))

# CELL 10 — settlement.html  (Settlement & Revenue)

gross_vol    = transactions[transactions["status"]=="success"]["amount"].sum()
total_fees   = gross_vol - total_settled
fee_rate_pct = total_fees / gross_vol * 100

# Chart s1 — Monthly revenue vs settled dual bar
s1 = go.Figure()
s1.add_trace(go.Bar(
    name="Gross revenue", x=MONTH_ORDER,
    y=monthly_settlement["revenue"],
    marker_color=BLUE, offsetgroup=0))
s1.add_trace(go.Bar(
    name="Settled amount", x=MONTH_ORDER,
    y=monthly_settlement["settled_amount"],
    marker_color=TEAL, offsetgroup=1))
s1.update_layout(**default_layout("Monthly gross revenue vs settled amount", 380))
s1.update_layout(
    barmode="group",
    legend=dict(orientation="h", y=1.12, x=0),
    xaxis=dict(showgrid=False, categoryorder="array", categoryarray=MONTH_ORDER),
    yaxis=dict(showgrid=True, gridcolor="#ebebeb", tickformat=",.0f", title="Amount ($)"))

# Chart s2 — Monthly fee amount + rate
s2 = make_subplots(specs=[[{"secondary_y":True}]])
s2.add_trace(go.Bar(
    name="Platform fee ($)", x=MONTH_ORDER,
    y=monthly_settlement["fee"],
    marker_color=ORANGE, marker_line_width=0),
    secondary_y=False)
s2.add_trace(go.Scatter(
    name="Fee rate (%)", x=MONTH_ORDER,
    y=monthly_settlement["fee_rate"],
    mode="lines+markers",
    line=dict(color=GRAY, width=2), marker=dict(size=7)),
    secondary_y=True)
s2.update_layout(**default_layout("Monthly platform fees & fee rate"))
s2.update_layout(
    legend=dict(orientation="h", y=1.12, x=0),
    xaxis=dict(showgrid=False, categoryorder="array", categoryarray=MONTH_ORDER))
s2.update_yaxes(title_text="Fee amount ($)", secondary_y=False,
                showgrid=True, gridcolor="#ebebeb", tickformat=",.0f")
s2.update_yaxes(title_text="Fee rate (%)", secondary_y=True,
                showgrid=False, ticksuffix="%")

# Chart s3 — Settlement by merchant
s3 = go.Figure()
s3.add_trace(go.Bar(
    name="Gross revenue",
    x=merchant_settlement["merchant_name"],
    y=merchant_settlement["revenue"],
    marker_color=BLUE, offsetgroup=0))
s3.add_trace(go.Bar(
    name="Settled amount",
    x=merchant_settlement["merchant_name"],
    y=merchant_settlement["settled"],
    marker_color=TEAL, offsetgroup=1))
s3.update_layout(**default_layout("Revenue vs settlement by merchant"))
s3.update_layout(
    barmode="group",
    legend=dict(orientation="h", y=1.12, x=0),
    xaxis=dict(showgrid=False, tickangle=-20),
    yaxis=dict(showgrid=True, gridcolor="#ebebeb", tickformat=",.0f", title="Amount ($)"))

kpis_s = f"""<div class="kpi-row kpi-row-4">
  {kpi("Gross transaction volume", f"${gross_vol:,.0f}")}
  {kpi("Total settled amount",     f"${total_settled:,.0f}")}
  {kpi("Total platform fees",      f"${total_fees:,.0f}")}
  {kpi("Platform fee rate",        f"{fee_rate_pct:.2f}%")}
</div>"""

body_s = f"""{kpis_s}
<div class="grid grid-1" style="margin-bottom:16px"><div class="card">{div(s1)}</div></div>
<div class="grid grid-1" style="margin-bottom:16px"><div class="card">{div(s2)}</div></div>
<div class="grid grid-1"><div class="card">{div(s3)}</div></div>"""

save("settlement.html", page_wrap(
    "settlement.html", BLUE, "💰",
    "Settlement & Revenue",
    "Gross volume, settlement payouts, and platform fee analysis",
    body_s))

# CELL 11 — geo.html  (Geographic & Currency)

top_country = by_country.iloc[0]["country"]
highest_avg = by_country.loc[by_country["avg_txn"].idxmax(), "country"]
n_currencies = by_currency["currency"].nunique()
n_countries  = by_country["country"].nunique()

# Chart g1 — Revenue by country (bar)
g1 = go.Figure(go.Bar(
    x=by_country["country"],
    y=by_country["revenue"],
    marker_color=[TEAL if c==top_country else BLUE for c in by_country["country"]],
    text=[f"${v:,.0f}" for v in by_country["revenue"]],
    textposition="outside", textfont=dict(size=11),
))
g1.update_layout(**default_layout("Total revenue by country"))
g1.update_layout(
    xaxis=dict(showgrid=False, title="Country"),
    yaxis=dict(showgrid=True, gridcolor="#ebebeb", tickformat=",.0f", title="Revenue ($)"),
    showlegend=False)

# Chart g2 — Transaction volume by country
g2 = go.Figure(go.Bar(
    x=by_country["country"],
    y=by_country["total"],
    marker_color=PURPLE,
    text=[f"{v:,}" for v in by_country["total"]],
    textposition="outside", textfont=dict(size=11),
))
g2.update_layout(**default_layout("Transaction volume by country"))
g2.update_layout(
    xaxis=dict(showgrid=False, title="Country"),
    yaxis=dict(showgrid=True, gridcolor="#ebebeb", title="Transactions"),
    showlegend=False)

# Chart g3 — Success rate by country
g3_colors = [RED if v < avg_sr else TEAL for v in by_country["sr"]]
g3 = go.Figure(go.Bar(
    x=by_country["country"],
    y=by_country["sr"],
    marker_color=g3_colors,
    text=[f"{v:.1f}%" for v in by_country["sr"]],
    textposition="outside", textfont=dict(size=11),
))
g3.add_hline(y=avg_sr, line_dash="dot", line_color=GRAY,
             annotation_text=f"Platform avg {avg_sr:.1f}%",
             annotation_position="top right")
g3.update_layout(**default_layout("Success rate by country"))
g3.update_layout(
    xaxis=dict(showgrid=False, title="Country"),
    yaxis=dict(range=[84,95], ticksuffix="%",
               showgrid=True, gridcolor="#ebebeb"),
    showlegend=False)

# Chart g4 — Currency revenue share (pie)
g4 = go.Figure(go.Pie(
    labels=by_currency["currency"],
    values=by_currency["revenue"],
    hole=0.55,
    marker=dict(colors=[BLUE, TEAL, AMBER]),
    textinfo="label+percent", textposition="outside", textfont=dict(size=12),
    showlegend=False,
))
g4.update_layout(**default_layout("Revenue share by currency"))
g4.update_layout(margin=dict(t=52,b=20,l=60,r=60))

# Chart g5 — Avg transaction value by country
g5 = go.Figure(go.Bar(
    x=by_country["country"],
    y=by_country["avg_txn"],
    marker_color=[ORANGE if c==highest_avg else AMBER for c in by_country["country"]],
    text=[f"${v:,.2f}" for v in by_country["avg_txn"]],
    textposition="outside", textfont=dict(size=11),
))
g5.update_layout(**default_layout("Average transaction value by country"))
g5.update_layout(
    xaxis=dict(showgrid=False, title="Country"),
    yaxis=dict(showgrid=True, gridcolor="#ebebeb", tickformat=",.0f", title="Avg txn value ($)"),
    showlegend=False)

kpis_g = f"""<div class="kpi-row kpi-row-4">
  {kpi("Countries",              str(n_countries))}
  {kpi("Currencies",             str(n_currencies))}
  {kpi("Top revenue country",    top_country)}
  {kpi("Highest avg txn value",  highest_avg)}
</div>"""

body_g = f"""{kpis_g}
<div class="grid grid-2" style="margin-bottom:16px">
  <div class="card">{div(g1)}</div>
  <div class="card">{div(g2)}</div>
</div>
<div class="grid grid-2" style="margin-bottom:16px">
  <div class="card">{div(g3)}</div>
  <div class="card">{div(g4)}</div>
</div>
<div class="grid grid-1"><div class="card">{div(g5)}</div></div>"""

save("geo.html", page_wrap(
    "geo.html", ORANGE, "🌏",
    "Geographic & Currency",
    "Country-level transaction performance and currency revenue breakdown",
    body_g))

# CELL 12 — index.html  (Storyboard / Executive Summary)

# Mini charts for the storyboard
# Mini 1 — Monthly revenue sparkline
idx1 = go.Figure(go.Scatter(
    x=MONTH_ORDER, y=monthly["revenue"],
    mode="lines+markers",
    line=dict(color=TEAL, width=2.5),
    marker=dict(size=7, color=TEAL),
    fill="tozeroy", fillcolor="rgba(29,158,117,0.10)", showlegend=False,
))
idx1.update_layout(**default_layout("Revenue trend  —  Jan–Aug 2024", 280))
idx1.update_layout(
    xaxis=dict(showgrid=False, categoryorder="array", categoryarray=MONTH_ORDER),
    yaxis=dict(showgrid=True, gridcolor="#ebebeb", tickformat=",.0f"))

# Mini 2 — Success rate + chargeback rate dual
idx2 = make_subplots(specs=[[{"secondary_y":True}]])
idx2.add_trace(go.Scatter(
    name="Success rate", x=MONTH_ORDER, y=monthly["success_rate"],
    mode="lines+markers", line=dict(color=TEAL, width=2),
    marker=dict(size=6, color=[RED if r<90 else TEAL for r in monthly["success_rate"]])),
    secondary_y=False)
idx2.add_trace(go.Scatter(
    name="CB rate (%)", x=monthly_cb["month_str"], y=monthly_cb["cb_rate"],
    mode="lines+markers", line=dict(color=AMBER, width=2, dash="dot"),
    marker=dict(size=6, color=AMBER)),
    secondary_y=True)
idx2.update_layout(**default_layout("Success rate vs chargeback rate", 280))
idx2.update_layout(
    legend=dict(orientation="h", y=1.15, x=0),
    xaxis=dict(showgrid=False, categoryorder="array", categoryarray=MONTH_ORDER))
idx2.update_yaxes(title_text="Success rate (%)", secondary_y=False,
                  range=[88,94], ticksuffix="%", showgrid=True, gridcolor="#ebebeb")
idx2.update_yaxes(title_text="CB rate (%)", secondary_y=True,
                  ticksuffix="%", showgrid=False)

# Finding cards
findings = [
    ("🔴 June Anomaly",
     f"card_declined failures spiked to <strong>566</strong> in June "
     f"(avg ~248/month), causing the success rate to drop to "
     f"<strong>89.5%</strong> and revenue to fall <strong>12.3% MoM</strong>. "
     f"Likely a temporary payment gateway / issuer issue."),
    ("⚠️ SkyFare Travel Risk",
     f"SkyFare Travel has the lowest success rate at <strong>86.9%</strong> "
     f"and is the #2 revenue merchant. A persistent underperformance that warrants "
     f"direct investigation with the gateway or issuer."),
    ("📈 Revenue Plateau",
     f"After a strong H1 peak of <strong>$994K</strong> (May), revenue has "
     f"declined two consecutive months to <strong>$808K</strong> in Aug, "
     f"a 18.7% drop. Volume remains stable, suggesting avg transaction size is shrinking."),
    ("🔄 Rising Chargebacks",
     f"Chargeback count grew from <strong>18 in Jan</strong> to a peak of "
     f"<strong>57 in June</strong>. Although rates remain below 0.5%, the "
     f"upward trend (Jan–Jun) warrants monitoring."),
]

recommendations = [
    ("Immediate", RED, [
        "Audit the card processing pipeline for June — identify the issuer or gateway that triggered the card_declined spike.",
        "Place SkyFare Travel on a performance improvement plan; investigate their specific decline codes.",
    ]),
    ("Short-term", AMBER, [
        "Implement real-time alerts for success rate drops below 90% or MoM revenue changes exceeding ±10%.",
        "Work with chargeback prevention vendors for the top 3 merchants by dispute count.",
    ]),
    ("Strategic", TEAL, [
        "Investigate the revenue plateau — are average transaction values falling, or is it a mix-shift?",
        "Expand SG and AU merchant base; both show above-average transaction values.",
        "Review fee rates across currencies — LKR-denominated merchants are lower-value per transaction.",
    ]),
]

def finding_card(icon_title, body_text):
    return f"""<div style="background:#fff;border:1px solid #e4e7ec;border-radius:12px;padding:16px 18px;">
      <div style="font-size:14px;font-weight:600;margin-bottom:8px;">{icon_title}</div>
      <div style="font-size:13px;color:#6b7280;line-height:1.65;">{body_text}</div>
    </div>"""

finding_grid = '<div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-bottom:16px;">'
for title, body in findings:
    finding_grid += finding_card(title, body)
finding_grid += "</div>"

rec_sections = ""
for section, color, items in recommendations:
    bullets = "".join(f'<li style="margin-bottom:7px">{i}</li>' for i in items)
    rec_sections += f"""<div style="margin-bottom:14px">
      <div style="font-size:12px;font-weight:600;text-transform:uppercase;
                  letter-spacing:.06em;color:{color};margin-bottom:8px">{section}</div>
      <ul style="padding-left:18px;font-size:13px;color:#374151;line-height:1.65">{bullets}</ul>
    </div>"""

rec_box = f"""<div style="background:#fff;border:1px solid #e4e7ec;border-radius:12px;
                          padding:20px 24px;margin-bottom:16px">
  <div style="font-size:15px;font-weight:600;margin-bottom:16px">Recommended actions</div>
  {rec_sections}
</div>"""

# Summary KPI row
kpis_idx = f"""<div class="kpi-row kpi-row-5" style="margin-bottom:20px">
  {kpi("Total transactions",   f"{kpi_global['txns']:,}",      "neutral")}
  {kpi("Total revenue",        f"${kpi_global['rev']:,.0f}",   "neutral")}
  {kpi("Avg success rate",     f"{kpi_global['sr']:.2f}%",     "neutral")}
  {kpi("Total chargebacks",    str(kpi_global['cbs']),         "neutral")}
  {kpi("Total settled",        f"${kpi_global['settled']:,.0f}","neutral")}
</div>"""

body_idx = f"""{kpis_idx}
<div class="grid grid-2" style="margin-bottom:16px">
  <div class="card">{div(idx1)}</div>
  <div class="card">{div(idx2)}</div>
</div>
<div style="font-size:15px;font-weight:600;margin-bottom:12px">Key findings</div>
{finding_grid}
{rec_box}"""

save("index.html", page_wrap(
    "index.html", "#1a1d23", "📋",
    "Storyboard",
    "Executive summary · CeylonCash payments data · Jan–Aug 2024",
    body_idx))

print("\n✅ All 7 dashboards saved to charts/")

# CELL 13 — Zip & Download

zip_name = "ceypay_dashboards.zip"
with zipfile.ZipFile(zip_name, "w", zipfile.ZIP_DEFLATED) as z:
    for fname in os.listdir("charts"):
        if fname.endswith(".html"):
            z.write(f"charts/{fname}", fname)
            print(f"  📦 Added: {fname}")

print(f"\n✅ ZIP created → {zip_name}")
files.download(zip_name)
print("✅ Download started — ceypay_dashboards.zip")